name: Auto Free Nodes

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Fetch and merge
      run: |
        mkdir -p data

        curl -L https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2 > data/1.txt
        curl -L https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/sub/sub_merge.txt > data/2.txt

        cat data/*.txt > sub.txt

    - name: Encode base64 (for Shadowrocket)
      run: |
        base64 sub.txt > sub_base64.txt

    - name: Commit
      run: |
        git config --global user.name "bot"
        git config --global user.email "bot@users.noreply.github.com"
        git add .
        git commit -m "update" || echo "no changes"
        git push
